---
- name: "Install nullmailer"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - nullmailer

- name: "Configure nullmailer remotes"
  ansible.builtin.template:
    dest: /etc/nullmailer/remotes
    src: nullmailer_remotes
    owner: mail
    group: mail
    mode: 0600
  notify: Restart nullmailer

- name: "Configure nullmailer adminaddr"
  ansible.builtin.template:
    dest: /etc/nullmailer/adminaddr
    src: nullmailer_adminaddr
    owner: root
    group: root
    mode: 0644
  notify: Restart nullmailer

- name: "Configure nullmailer allmailfrom"
  ansible.builtin.template:
    dest: /etc/nullmailer/allmailfrom
    src: nullmailer_allmailfrom
    owner: root
    group: root
    mode: 0644
  when: nullmailer_allmailfrom is defined
  notify: Restart nullmailer

- name: Enable nullmailer
  ansible.builtin.service:
    name: nullmailer
    state: started
    enabled: true
