---
- name: "install nullmailer"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - nullmailer

- name: "configure nullmailer remotes"
  template:
    dest: /etc/nullmailer/remotes
    src: nullmailer_remotes
    owner: mail
    group: mail
    mode: 0600
  notify: restart nullmailer

- name: "configure nullmailer adminaddr"
  template:
    dest: /etc/nullmailer/adminaddr
    src: nullmailer_adminaddr
    owner: root
    group: root
    mode: 0644
  notify: restart nullmailer

- name: "configure nullmailer allmailfrom"
  template:
    dest: /etc/nullmailer/allmailfrom
    src: nullmailer_allmailfrom
    owner: root
    group: root
    mode: 0644
  when: nullmailer_allmailfrom is defined
  notify: restart nullmailer

- name: enable nullmailer
  service:
    name: nullmailer
    state: started
    enabled: true
