---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: nullmailer-ubuntu-1804
    image: ubuntu:18.04
    # image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
  - name: nullmailer-ubuntu-1604
    image: ubuntu:16.04
  - name: nullmailer-debian-10-buster
    image: debian:buster
  - name: nullmailer-debian-9-stretch
    image: debian:stretch
  - name: nullmailer-debian-8-jessie
    image: debian:jessie
provisioner:
  name: ansible
