---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
  enabled: false
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint --offline --exclude molecule
platforms:
  - name: nullmailer-ubuntu-2404
    image: ubuntu:24.04
    command: /lib/systemd/systemd
    privileged: true
    dockerfile: Dockerfile.j2
  - name: nullmailer-ubuntu-2204
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    privileged: true
    dockerfile: Dockerfile.j2
  - name: nullmailer-debian-13-trixie
    image: debian:trixie
    command: /lib/systemd/systemd
    privileged: true
    dockerfile: Dockerfile.j2
  - name: nullmailer-debian-12-bookworm
    image: debian:bookworm
    command: /lib/systemd/systemd
    privileged: true
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$ANSIBLE_ROLES_PATH:$MOLECULE_PROJECT_DIRECTORY/..:$HOME/.ansible/roles"
  env:
    # https://github.com/ansible-community/molecule-plugins/
    # until molecule-docker has a new release, we need to do this:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
